# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

Exception: ignored

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)

1.23.5


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null=np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
arr=np.array([1,3,5,7])
print(arr.size*arr.itemsize)

32


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null=np.zeros(10)
null[4]=1
print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr=np.flip(arr)
print(arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
arr1=np.arange(0,9)
arr1=arr1.reshape(3,3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr2=np.array([1,2,0,0,4,0])
print(np.nonzero(arr2))
for i in range(0,len(arr2)):
  if arr2[i]==0:
    continue
  else:
    print(i)


(array([0, 1, 4]),)
0
1
4


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
arr=np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
from numpy import random
arr2=random.randint(15,size=(3,3,3))
print(arr2)

[[[ 2  2  2]
  [ 3  1  1]
  [12  6 10]]

 [[13  8  9]
  [ 3 13 14]
  [ 5  7  5]]

 [[ 0  4  3]
  [10  6 14]
  [ 8 11  4]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr3=random.randint(15,size=(10,10))
print('min=',np.min(arr3),' max= ',np.max(arr3))

min= 0  max=  14


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr4=random.randint(100,size=30)
print(np.mean(arr4))

55.96666666666667


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr=np.ones((4,4))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
arr=np.ones((4,4))
arr2=np.pad(arr,pad_width=1,constant_values=0)
print(arr2)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(np.nan in set([np.nan]))
print(0.3==3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
arr=np.diag([1,2,3,4],k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1  # Setting alternate rows starting from the second row with alternate columns to 1
x[::2, 1::2] = 1  # Setting alternate rows starting from the first row with alternate columns to 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
arr=np.tile([[0,1],[1,0]],(4,4))
print(arr)
np.shape(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


(8, 8)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
from numpy import random
arr=random.randint(15,size=(5,5))
print(arr)
arr=arr/np.max(arr)
print(arr)
arr=arr.astype('S')
print(arr.dtype)
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)


[[ 9  5 10  2 11]
 [10 12 13  6  0]
 [ 0  3  5  4 13]
 [ 3  9  2 12 10]
 [13 12  8 12  4]]
[[0.69230769 0.38461538 0.76923077 0.15384615 0.84615385]
 [0.76923077 0.92307692 1.         0.46153846 0.        ]
 [0.         0.23076923 0.38461538 0.30769231 1.        ]
 [0.23076923 0.69230769 0.15384615 0.92307692 0.76923077]
 [1.         0.92307692 0.61538462 0.92307692 0.30769231]]
|S32


ValueError: ignored

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([
    ("r", np.ubyte, 1),
    ("g", np.ubyte, 1),
    ("b", np.ubyte, 1),
    ("a", np.ubyte, 1)
    ])


[255   0   0]
[  0 255   0]
[  0   0 255]
[255 255 255]


<ipython-input-16-7f95434f22ac>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
arr1=random.randint(15,size=(5,3))
arr2=random.randint(15,size=(3,2))
x=np.dot(arr1,arr2)
print(x)

[[ 21  57]
 [ 57  72]
 [210 196]
 [ 13  16]
 [ 80  92]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a=np.arange(15)
a[(a>3)&(a<8)]*=-1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=np.arange(5)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: ignored

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
arr=np.array([1,2,3,4,5,6.5,8.4,9.6])
arr=np.round(arr)
print(arr[-3:])
print(arr)

[ 6.  8. 10.]
[ 1.  2.  3.  4.  5.  6.  8. 10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
from numpy import random
arr1=random.randint(15,size=(3,3))
arr2=random.randint(15,size=(3,3))
print(arr1)
print(arr2)
np.intersect1d(arr1,arr2)

[[ 4  1 11]
 [ 4  8 11]
 [ 7  9  3]]
[[ 7  9  5]
 [ 4  8  3]
 [10 13  5]]


array([3, 4, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
print(np.datetime64('today','D'))

2023-12-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
print(np.arange('2016-07','2016-08',dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:

A=np.array([1,3,5],dtype=int)
print(A)
B=np.array([8,3,4],dtype=int)
print(B)
B+=A
B*=(-A/2).astype(int)
print(B)

[1 3 5]
[8 3 4]
[  0  -6 -18]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
arr = np.random.rand(3) * 6
print(arr)
method1 = np.floor(arr).astype(int)
print(method1)

method2 = np.trunc(arr).astype(int)
print(method2)

method3 = arr.astype(int)
print(method3)

method4 = np.int_(arr)
print(method4)

[2.55041898 0.35307203 1.51532166]
Method 1: [2 0 1]
Method 2: [2 0 1]
Method 3: [2 0 1]
Method 4: [2 0 1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
arr=np.zeros((5,5))
print(arr)
arr+=np.arange(5)
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generator():
  lst=[1,3,4]
  for i in lst:
    yield i
arr = np.fromiter(generator(), dtype=float)
print(arr)


[1. 3. 4.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
arr=random.rand(10)
print(arr)

[0.94241229 0.04850552 0.13986488 0.762309   0.82509088 0.19424721
 0.07722461 0.20306361 0.84124931 0.2699133 ]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr=random.randint(10,size=10)
arr=np.sort(arr)
print(arr)

[2 3 4 5 6 6 8 8 9 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [3]:
import numpy as np
arr1=np.zeros((5,5))
arr2=np.zeros((5,5))
np.array_equal(arr1,arr2)

True

#### 43. Make an array immutable (read-only) (★★☆)

In [6]:
arr1=np.zeros((5,5))
arr1.flags.writeable=False
arr1[0,0]=1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [9]:
import numpy as np
from numpy import random
arr = np.random.randint(15,size=(10, 2))
print(arr)
x, y = arr[:, 0], arr[:, 1]
r = np.sqrt(x**2 + y**2)
print(r)
theta = np.arctan2(y, x)
print(theta)
print(np.column_stack([r, theta]))


[[11  6]
 [10  2]
 [ 1  9]
 [ 6  2]
 [10  1]
 [13  3]
 [ 9  8]
 [ 0 12]
 [ 1  7]
 [ 6 10]]
[12.52996409 10.19803903  9.05538514  6.32455532 10.04987562 13.34166406
 12.04159458 12.          7.07106781 11.66190379]
[0.49934672 0.19739556 1.46013911 0.32175055 0.09966865 0.22679885
 0.72664234 1.57079633 1.42889927 1.03037683]
[[12.52996409  0.49934672]
 [10.19803903  0.19739556]
 [ 9.05538514  1.46013911]
 [ 6.32455532  0.32175055]
 [10.04987562  0.09966865]
 [13.34166406  0.22679885]
 [12.04159458  0.72664234]
 [12.          1.57079633]
 [ 7.07106781  1.42889927]
 [11.66190379  1.03037683]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [6]:
arr = np.random.randint(15,size=(10))
max_value = np.max(arr)
print(max_value)
print(arr)
arr[arr == max_value] = 0
print(arr)

12
[ 3 12  6  3  4  7  5  4 10  0]
[ 3  0  6  3  4  7  5  4 10  0]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [13]:
x=np.zeros((5,5),[('a',float),('b',float)])
x['a'],x['b']=np.meshgrid(np.linspace(0,10,5),np.linspace(0,10,5))
print(x)


[[( 0. ,  0. ) ( 2.5,  0. ) ( 5. ,  0. ) ( 7.5,  0. ) (10. ,  0. )]
 [( 0. ,  2.5) ( 2.5,  2.5) ( 5. ,  2.5) ( 7.5,  2.5) (10. ,  2.5)]
 [( 0. ,  5. ) ( 2.5,  5. ) ( 5. ,  5. ) ( 7.5,  5. ) (10. ,  5. )]
 [( 0. ,  7.5) ( 2.5,  7.5) ( 5. ,  7.5) ( 7.5,  7.5) (10. ,  7.5)]
 [( 0. , 10. ) ( 2.5, 10. ) ( 5. , 10. ) ( 7.5, 10. ) (10. , 10. )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)