### Questions 1

Create a matrix of 5x5 with random integers, after that swap its first and last rows.

In [98]:
import numpy as np
from numpy import random

arr1=random.randint(15,size=(5,5))
arr2=arr1
print(arr2)
arr2[0,:],arr2[4,:]=arr2[4,:].copy(),arr2[0,:].copy()
print(arr2)

[[14  9  4 13  8]
 [ 0 11 14 11  1]
 [10  3  7  4  5]
 [ 3 12  0 13 10]
 [11  4 14  1  1]]
[[11  4 14  1  1]
 [ 0 11 14 11  1]
 [10  3  7  4  5]
 [ 3 12  0 13 10]
 [14  9  4 13  8]]


### Question 2

Create a 2D array, remove all rows that contain at least one zero.

In [77]:
arr1=random.randint(15,size=(3,3))
print(arr1)
print(np.size(arr1))
x=0
for i in range(3):
    if x in arr1[i,:]:
        arr2=arr1[i+1,:]
    else:
        continue
print(arr1)

[[12 13  0]
 [11  9  4]
 [ 6  7  0]]
9


IndexError: index 3 is out of bounds for axis 0 with size 3

### Question 3

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

In [18]:
arr1=np.array([1.00000000+0j,0.70710678+0.70710678j])
print(arr1)
list=arr1.split('+')
print(list)

[1.        +0.j         0.70710678+0.70710678j]


AttributeError: 'numpy.ndarray' object has no attribute 'split'

### Question 4

Write a NumPy program to remove the duplicate elements of an array.<br>
Original array:
[10 10 20 20 30 30]


In [21]:
arr1=np.array([10,10,20,20,30,30])

for i in range(0,len(arr1)-1):
    for j in range(i+1,len(arr1)):
        if arr1[i]==arr1[j]:
            arr2=np.array([arr1[0:i],arr1[i:j],arr1[j+1:]])

print(arr2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

### Question 5

Write a NumPy program to create a 3x3x3 array with random values.

In [22]:
arr1=random.randint(15,size=(3,3,3))
print(arr1)

[[[ 3  5 13]
  [12  8  1]
  [ 6 13  8]]

 [[ 6  6 14]
  [ 2  7 13]
  [10  8  6]]

 [[14  1  4]
  [ 1 13  6]
  [ 6  2 10]]]


### Question 6

Write a NumPy program to create a random vector of size 10 and sort it.
<b>Note:<\b> Do not use builtin sorting function

In [92]:
arr1=random.randint(15,size=(10))
def sorting(arr1):
    print(arr1)
    for i in range(0,len(arr1)):
        for j in range(0,len(arr1)):
            if arr1[i]<arr1[j]:
                temp=arr1[j]
                arr1[j]=arr1[i]
                arr1[i]=temp
    print(arr1)
sorting(arr1)
arr1=np.array([[10,40],[30,20]])
arr1=arr1.flatten()
sorting(arr1)
arr1=arr1.reshape(2,2)
print(arr1)

[ 5  1  7  9  1  8  0 14  3  4]
[ 0  1  1  3  4  5  7  8  9 14]
[10 40 30 20]
[10 20 30 40]
[[10 20]
 [30 40]]


### Question 7

Write a NumPy program to check two random arrays are equal or not.

In [73]:
arr1=random.randint(15,size=(10))
arr2=random.randint(15,size=(10))
arr3=np.array([10, 4,  3,  5,  3,  9,  1,  2,  6, 8])
arr4=np.array([10, 4,  3,  5,  3,  9,  1,  2,  6, 8])

def equal(arr1,arr2):
    print(arr1)
    print(arr2)
    if(len(arr1)!=len(arr2)):
        print('arrays are not equal')
    else:
        for i in range(len(arr1)):
            if arr1[i]==arr2[i]:
                continue
            else:
                print('arrays are not equal')
                return
    print('arrays are equal')

equal(arr1,arr2)
equal(arr3,arr4)


[13 12 10  8  6 13  1  9  0  0]
[ 5  3  3  9 10  7  9  2 10 10]
arrays are not equal
[10  4  3  5  3  9  1  2  6  8]
[10  4  3  5  3  9  1  2  6  8]
arrays are equal


### Question 8 

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.<br>

Original array:<br>
[[10 40]<br>
[30 20]]

In [96]:
arr1=np.array([[10,40],[30,20]])
    
def sorting(arr1):
    print(arr1)
    for i in range(0,len(arr1)):
        for j in range(0,len(arr1)):
            if arr1[i]<arr1[j]:
                temp=arr1[j]
                arr1[j]=arr1[i]
                arr1[i]=temp
print(arr1)
arr1=arr1.flatten()
sorting(arr1)
arr1=arr1.reshape(2,2)
print(arr1)

[[10 40]
 [30 20]]
[10 40 30 20]
[[10 20]
 [30 40]]


### Question 9

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.<br>

Original array:<br>
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]

In [67]:
arr1=[-1.6,-1.5,-0.3,0.1,1.4,1.8,2 ]
def floor_ceil_trunc(arr):
    print(arr1)
    arr2=np.trunc(arr1)
    print('truncated value ',arr2)
    arr3=np.ceil(arr1)
    print('ceiling value ',arr3)
    arr4=np.floor(arr1)
    print('floor value ',arr4)
floor_ceil_trunc(arr1)

[-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2]
truncated value  [-1. -1. -0.  0.  1.  1.  2.]
ceiling value  [-1. -1. -0.  1.  2.  2.  2.]
floor value  [-2. -2. -1.  0.  1.  1.  2.]


### Questions 10

Write a NumPy program to display all the dates for the month of March, 2017

In [44]:
print(np.arange('2017-03','2017-04',dtype='datetime64[D]'))

['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


### Question 11

Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.

In [48]:
arr1=np.arange('2017-03-01','2017-03-02',dtype='datetime64[h]')
print(arr1)

['2017-03-01T00' '2017-03-01T01' '2017-03-01T02' '2017-03-01T03'
 '2017-03-01T04' '2017-03-01T05' '2017-03-01T06' '2017-03-01T07'
 '2017-03-01T08' '2017-03-01T09' '2017-03-01T10' '2017-03-01T11'
 '2017-03-01T12' '2017-03-01T13' '2017-03-01T14' '2017-03-01T15'
 '2017-03-01T16' '2017-03-01T17' '2017-03-01T18' '2017-03-01T19'
 '2017-03-01T20' '2017-03-01T21' '2017-03-01T22' '2017-03-01T23']


### Question 12

Write a NumPy program to concatenate element-wise two arrays of string.<br>
<b>Example <\b>
Array1:<br>
['Python' 'PHP']<br>
Array2:<br>
[' Java' ' C++']<br>
new array:<br>
['Python Java' 'PHP C++']<br>

In [65]:
arr1=np.array(['Python','PHP'],dtype=str)
arr2=np.array(['Java','C++'],dtype=str)
def concat(a,b):

    print(arr1)
    print(arr2)
    arr3=np.zeros(max(len(arr1),len(arr2))).astype(str)
    print(arr3)
    for i in range(len(arr3)):
        arr3[i]=arr1[i]+arr2[i]
    print(arr3)
concat(arr1,arr2)

['Python' 'PHP']
['Java' 'C++']
['0.0' '0.0']
['PythonJava' 'PHPC++']
